language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: notify_start
    if: tag is present
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=test

    - stage: notify_start
      script: deploy/notify-start.sh
      install: skip

    - stage: notify
      script: deploy/notify.sh
      install: skip

    - stage: deploy
      name: Industrial Distribution
      script: deploy/index.js inddist caprica
      install: skip

    - stage: deploy
      name: Manufacturing.net
      script: deploy/index.js manufacturing caprica
      install: skip

    - stage: deploy
      name: Food Manufacturing
      script: deploy/index.js foodmanufacturing caprica
      install: skip

    - stage: deploy
      name: IMPO
      script: deploy/index.js impomag caprica
      install: skip

    - stage: deploy
      name: Manufacturing Business Technology
      script: deploy/index.js mbtmag caprica
      install: skip

    # - stage: deploy
    #   name: Industrial Equipment News
    #   script: deploy/index.js ien caprica
    #   install: skip

    # - stage: deploy
    #   name: Manufacturing Business Technology
    #   script: deploy/index.js cannabisequipmentnews caprica
    #   install: skip

    # - stage: deploy
    #   name: Manufacturing Business Technology
    #   script: deploy/index.js designdevelopmenttoday caprica
    #   install: skip
