version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.24
  entrypoint: ["node"]
  working_dir: /root
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  # @todo the recaptcha values should be removed (?) once contact-us is moved to core.
  RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY-(unset)}
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  # @todo the sendgrid values should be removed once the @parameter1/base-cms-mailer service is created.
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: developer@endeavorb2b.com
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  OMEDA_APP_ID: ${OMEDA_APP_ID-(unset)}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-(unset)}

  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://tauron.graphql.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://tauron.oembed.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://tauron.rss.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://tauron.sitemaps.base.parameter1.com}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10102}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10402}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10202}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10302}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  id:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/inddist.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-id.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9710
      LIVERELOAD_PORT: 19710
      TENANT_KEY: indm_multi
      SITE_ID: 5d76bf9eed61522e008b456b
    hostname: www-indm-id.dev.parameter1.com
    ports:
      - "9710:80"
      - "19710:19710"

  mnet:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/manufacturing.net
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-mnet.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9711
      LIVERELOAD_PORT: 19711
      TENANT_KEY: indm_multi
      SITE_ID: 5d76bfaf665fc42e008b4569
    hostname: www-indm-mnet.dev.parameter1.com
    ports:
      - "9711:80"
      - "19711:19711"

  fm:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/foodmanufacturing.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-fm.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9712
      LIVERELOAD_PORT: 19712
      TENANT_KEY: indm_multi
      SITE_ID: 5d76bfdd665fc42e008b456b
    hostname: www-indm-fm.dev.parameter1.com
    ports:
      - "9712:80"
      - "19712:19712"

  impo:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/impomag.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-impo.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9713
      LIVERELOAD_PORT: 19713
      TENANT_KEY: indm_multi
      SITE_ID: 5d76bfe40827e83a008b456f
    hostname: www-indm-impo.dev.parameter1.com
    ports:
      - "9713:80"
      - "19713:19713"

  mbt:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/mbtmag.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-mbt.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9714
      LIVERELOAD_PORT: 19714
      TENANT_KEY: indm_multi
      SITE_ID: 5d76c0287c94042e008b456b
    hostname: www-indm-mbt.dev.parameter1.com
    ports:
      - "9714:80"
      - "19714:19714"

  ien:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/ien.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-ien.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9715
      LIVERELOAD_PORT: 19715
      TENANT_KEY: indm_multi
      SITE_ID: 5669a4f16cdeeaf8598b4579
    hostname: www-indm-ien.dev.parameter1.com
    ports:
      - "9715:80"
      - "19715:19715"

  ien-global:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/global.ien.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-ien-global.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9015
      LIVERELOAD_PORT: 19015
      TENANT_KEY: indm_multi
      SITE_ID: 5669a4f16cdeeaf8598b4579
    hostname: www-indm-ien-global.dev.parameter1.com
    ports:
      - "9015:80"
      - "19015:19015"

  cen:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/cannabisequipmentnews.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-cen.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9716
      LIVERELOAD_PORT: 19716
      TENANT_KEY: indm_multi
      SITE_ID: 5bc762d5adff35d154716639
    hostname: www-indm-cen.dev.parameter1.com
    ports:
      - "9716:80"
      - "19716:19716"

  ddt:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/designdevelopmenttoday.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-ddt.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9717
      LIVERELOAD_PORT: 19717
      TENANT_KEY: indm_multi
      SITE_ID: 5af4890775a254af9e0041a7
    hostname: www-indm-ddt.dev.parameter1.com
    ports:
      - "9717:80"
      - "19717:19717"

  mdd:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/medicaldesigndevelopment.com
    environment:
      <<: *env
      <<: *env-tauron
      HOST: www-indm-mdd.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9718
      LIVERELOAD_PORT: 19718
      TENANT_KEY: indm_multi
      SITE_ID: 6220f722417c94af0e8b45ca
    hostname: www-indm-mdd.dev.parameter1.com
    ports:
      - "9718:80"
      - "19719:19718"
