version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  # @todo the recaptcha values should be removed (?) once contact-us is moved to core.
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  # @todo the sendgrid values should be removed once the @base-cms/mailer service is created.
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: developer@endeavorb2b.com
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-caprica: &env-caprica
  GRAPHQL_URI: ${GRAPHQL_URI-https://caprica.graphql-staging.base-cms.io}
  OEMBED_URI: ${OEMBED_URI-https://caprica.oembed-staging.base-cms.io}
  RSS_URI: ${RSS_URI-https://caprica.rss-staging.base-cms.io}
  SITEMAPS_URI: ${SITEMAPS_URI-https://caprica.sitemaps-staging.base-cms.io}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10002}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10013}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10011}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10009}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  inddist:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/inddist
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 9710
      LIVERELOAD_PORT: 19710
      TENANT_KEY: indm_all
      CDN_IMAGE_HOSTNAME: base.imgix.net
      CDN_ASSET_HOSTNAME: cdn.inddist.com
    ports:
      - "9710:80"
      - "19710:19710"

  manufacturing:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/manufacturing
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 9711
      LIVERELOAD_PORT: 19711
      TENANT_KEY: indm_all
      CDN_IMAGE_HOSTNAME: base.imgix.net
      CDN_ASSET_HOSTNAME: cdn.manufacturing.net
    ports:
      - "9711:80"
      - "19711:19711"

  foodmanufacturing:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/foodmanufacturing
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 9712
      LIVERELOAD_PORT: 19712
      TENANT_KEY: indm_all
      CDN_IMAGE_HOSTNAME: base.imgix.net
      CDN_ASSET_HOSTNAME: cdn.foodmanufacturing.com
    ports:
      - "9712:80"
      - "19712:19712"

  impomag:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/impomag
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 9713
      LIVERELOAD_PORT: 19713
      TENANT_KEY: indm_all
      CDN_IMAGE_HOSTNAME: base.imgix.net
      CDN_ASSET_HOSTNAME: cdn.impomag.com
    ports:
      - "9713:80"
      - "19713:19713"

  mbtmag:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/mbtmag
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 9714
      LIVERELOAD_PORT: 19714
      TENANT_KEY: indm_all
      CDN_IMAGE_HOSTNAME: base.imgix.net
      CDN_ASSET_HOSTNAME: cdn.mbtmag.com
    ports:
      - "9714:80"
      - "19714:19714"

  # ien:
  #   <<: *node
  #   <<: *site-cmd
  #   working_dir: /root/sites/ien
  #   environment:
  #     <<: *env
  #     <<: *env-caprica
  #     PORT: 80
  #     EXPOSED_PORT: 9715
  #     LIVERELOAD_PORT: 19715
  #     TENANT_KEY: indm_ien
  #     CDN_IMAGE_HOSTNAME: base.imgix.net
  #     CDN_ASSET_HOSTNAME: cdn.ien.com
  #   ports:
  #     - "9715:80"
  #     - "19715:19715"

  # cannabisequipmentnews:
  #   <<: *node
  #   <<: *site-cmd
  #   working_dir: /root/sites/cannabisequipmentnews
  #   environment:
  #     <<: *env
  #     <<: *env-caprica
  #     PORT: 80
  #     EXPOSED_PORT: 9716
  #     LIVERELOAD_PORT: 19716
  #     TENANT_KEY: indm_cen
  #     CDN_IMAGE_HOSTNAME: base.imgix.net
  #     CDN_ASSET_HOSTNAME: cdn.cannabisequipmentnews.com
  #   ports:
  #     - "9716:80"
  #     - "19716:19716"

  # designdevelopmenttoday:
  #   <<: *node
  #   <<: *site-cmd
  #   working_dir: /root/sites/designdevelopmenttoday
  #   environment:
  #     <<: *env
  #     <<: *env-caprica
  #     PORT: 80
  #     EXPOSED_PORT: 9717
  #     LIVERELOAD_PORT: 19717
  #     TENANT_KEY: indm_ddt
  #     CDN_IMAGE_HOSTNAME: base.imgix.net
  #     CDN_ASSET_HOSTNAME: cdn.designdevelopmenttoday.com
  #   ports:
  #     - "9717:80"
  #     - "19717:19717"
